function _AceGScript(O,T){for(var i=0;i<O.val.length;i++){var _AR=O.val[i];if(_AR[3]==T){return O.val[i];};}}
function _AceCDomain(H,C){var _C=C.split(',')
for(var i in _C){var _CDM=_C[i];if(H.indexOf(_CDM)!=-1){return _CDM;}}}
function _IDV(a){return(typeof a!='undefined')?1:0}
function _RPS(a,b,c){var d=a.indexOf(b),e=b.length>0?c.length:1;while(a&&d>=0){a=a.substring(0,d)+c+a.substring(d+b.length);d=a.indexOf(b,d+e);}
return a}
var _ACE_GUID=_AceGScript(_AceGID,'AM');if(typeof(_AceGID)=='object'){if((typeof(_AMLog)=='undefined')&&(typeof(_ACE_GUID)!='undefined')){if(!_IDV(_AceCkdm))
var _AceCkdm='';if(!_IDV(_AceCrsdm))
var _AceCrsdm='';var _CRS=_AceCkdm?_AceCkdm:'';var _CRD=_AceCrsdm?_AceCrsdm:'';var _MCD=_CRS?_AceCDomain(_ACE_GUID[0],_CRS):_ACE_GUID[0];var _MUD=_ACE_GUID[1];var _MUC=_ACE_GUID[2];var _MPY=_ACE_GUID[4];var _AKC=_ACE_GUID[5];var _CSD=_CRD.split(',');_AKC=((_AKC=='')?_AKC+'':_AKC+',')+'utm_medium,utm_campaign,utm_term,utm_content';function AM_URL_CUR(_URL){if(_URL.indexOf(';')>0){var _ttRL=_URL;var _spt1=_URL.indexOf(';');var _spt2=_URL.indexOf('?');if(_spt1<_spt2){_ttRL=_ttRL.substr(0,_spt1);_URL=_ttRL+_URL.substr(_spt2,_URL.length-_spt1);}else{_URL=_URL.substr(0,_spt1);}};if(typeof(_AKC)!='undefined'){var _R_a=_AKC.split(',');var _ak2='';var _ak_list=_URL.split('&');for(var i=0;i<_ak_list.length;i++){var cnt=0;for(var a=0;a<_R_a.length;a++){if(_ak_list[i].indexOf(_R_a[a])==0)
cnt++;};if(cnt>0)
continue;if(_ak_list[i].indexOf('acekw=')==0){_ak_list[i]=_ak_list[i].replace('acekw=','kw=');};if(_ak2!='')
_ak2+='&';_ak2+=_ak_list[i];};if(_ak2!=''){_URL=_ak2;};return _URL;}else{return _URL;};};var _AMLog=[];var _AMSync=(function(_ug,_as){_as.cg=function(v){var aq='';var s=v;var ss=0;var se=0;var dc=document.cookie;if(dc.length>0){ss=dc.lastIndexOf(s+"=");if(ss!=-1){ss=ss+s.length+1;se=dc.indexOf(";",ss);if(se==-1){se=dc.length;};aq=unescape(dc.substring(ss,se));return aq;};}
return'';};_as.dmp=function(){var bd=String(_as.cg("_fbp"));var uci=String((document.cookie.indexOf("ACEUCI=")>-1)?1:'');return(bd.length>0?bd:'0')+'.0.'+uci.length;};return _as;})('',window._AMSync||[]);var AM_Mobile=(function(){var _u={gd:'gmb.acecounter.com',cd:_MCD,ud:_MUD,uid:_MUC,sv:20240805,st:(30*60),py:_MPY};var _t={u:'unknown',d:'undefined',n:'null',m:'number',um:'undefined_member',re:'!|~| |&|"|<|>|[&=":,./?~!<>@%#$^&*()";]',Lp:'a.tagName=="SPAN"||a.tagName=="IMG"||a.tagName=="B" || a.tagName=="I" || a.tagName== "U" || a.tagName== "FONT" || a.tagName=="STRONG" || a.tagName=="I" || a.tagName=="A" || a.tagName=="AREA"',l:'load',c:'click',j:'javascript:',f:'function'};var _f={u:decodeURIComponent,e:encodeURIComponent,url:String(AM_URL_CUR(document.URL)),ref:document.referrer!=''?document.referrer:'bookmark',ei:function(s,t){return s.indexOf(t);},d:function(s){var r=String(s);return r.toUpperCase();},f:function(o){var a;a=o;if(_f.d(a.tagName)=='A'||_f.d(a.tagName)=='AREA'){return a;}else if(_f.d(a.tagName)=='BODY'){return 0;}else{return _f.f(a.parentNode);}},hr:function(u,t){var r=String(u).replace(/http:\/\/|https:\/\//gi,"");var v=1024;var s=r.length;if(s>v){if(t=='u'){r='URLblockade:'+s;}else{r=r.substring(0,v);}};if(t=='h'){return r.split('/')[0];};return r;},ea:function(c,f){var wd;if(c=='mousedown'){wd=window.document;}else{wd=window;}
if(wd.addEventListener){wd.addEventListener(c,f,false)}else if(wd.attachEvent){wd.attachEvent("on"+c,f)}},rc:function(s){var sr=_f.tg(s+'',_t.re);sr=sr.replace(/\_/g,'');return sr.substring(0,512);},ua:navigator.userAgent,lg:(typeof(navigator.language)!=_t.d)?navigator.language.toLowerCase():(typeof(navigator.userLanguage)!=_t.d)?navigator.userLanguage.toLowerCase():'',pcm:(typeof(window.orientation)!=_t.d?1:0),tz:function(){var t=20;t=Math.floor((new Date()).getTimezoneOffset()/60)+29;if(t>24)
t=t-24;return t;},tg:function(s,u,o){var us=u;var c='';c=String(s.replace(/<[^<|>]*>/gi,""));if(typeof(u)!=_t.d){if(typeof(o)!=_t.d){us=u.replace(o,'');}
c=eval("c.replace(/"+us+"/g,'')");};return c;},tgc:function(s){return String(s).replace(/[#&^@]/g,'');},iN:function(s){s+='';s=s.replace(/^\s*|\s*$/g,'');if(s==''||isNaN(s)!=false){return false;};return true;},ct:function(o){var a=0,p=0;var b='',om='',c='',d='',e='';if((_f.iN(o.qy)!=true)||(o.pn.length==0)||(o.am.length==0)||(o.qy.length==0)||(o.qy=='0')){return 0;};a=o.qy;b=_f.tgc(o.ct);c=_f.tgc(o.pn);e=o.pd;d=String(o.am);p=parseInt(d.replace(/[^0-9.]/g,""));if(typeof(o.onm)!='undefined'){om=_f.tgc(o.onm);}
return{pn:c,at:p,ct:b,qy:a,pd:e,onm:om};},t:function(){var c=String(Math.random()*1000000000).replace(".","");var t=Math.floor(new Date().getTime()/1000);var sr=t+''+c.substr(0,9);return{s:sr,p:sr};},ti:function(a){return parseInt(a.substr(0,10));},uq:function(){var cc=Math.floor(new Date().getTime());var a="";var sr="";var c="0A1B2C3D4EFGH5IJ6K7L8M9N0OPQURSTUVWXYZ";for(var i=0;i<6;i++){sr+=c.substr(Math.floor(Math.random()*39),1);}
a=cc+sr;return a+'';},nm:function(st){var v=String(st);var r='';for(var i=0;i<v.length;i++){if(!isNaN(v.charAt(i))){r+=v.charAt(i);};}
return(r!=''?r:v);},n:function(s){var str=s+"";var ret="";for(var i=0;i<str.length;i++){var at=str.charCodeAt(i);var ch=String.fromCharCode(at);if(at==10||at==32||at==35){ret+=''+ch.replace(ch,'');}else if(at==34||at==39){ret+=''+ch.replace(ch,' ');}else{ret+=''+ch;}}
return ret;},g:function(sr){var r='';var ar='';r=sr.substr(_f.ei(sr,'{'),sr.length);r=r.replace('{','');r=r.replace('}','');return r;},gP:function(nm){var curURL=location.search.substr(location.search.indexOf("?")+1);var svalue="";curURL=curURL.split("&");for(var i=0;i<curURL.length;i++){tmp=curURL[i].split("=");if([tmp[0]]==nm){svalue=tmp[1];}}
return svalue;},uacs:function(n){var cnt=0;var str="";for(var i=0;i<n.length;i++){var ns=n.substr(cnt,1);if(isNaN(ns)){str+=Math.round(ns.charCodeAt(0));}else{str+=ns;}
cnt++;}
return str.substring(0,19);},sse:function(p1,p2){if(window.location.search.indexOf('aas')!=-1){var asr=_f.gP('aas').split('|');var asrr=asr[0];if(asr[1]!=''&&asr[1]!=_t.d){asrr=asr[1];}
_s.cs('AS',asr[0]+'|'+_f.t().p+'|'+asrr+'|'+0+'|'+'bookmark',0,'/','');_s.cs('AU',_f.gP('aau'),(1000*86400*365)*10,'/','');}
var s=_s.cg('AS');var sts='';var q=_f.uq();var c=_s.cg('AU');var r=_s.cg('AR');var sv=s.split("|");var rt=0;var a='';var t=_f.t();var v=0;var cn=2;var cn2=1;var c1=(_f.u(p1).indexOf('&md=b')>-1)?1:0;var g="";var c2=(p2.length>0)?t.s:0;var ct=c.split("|");var ts=t.s+'|'+t.p+'|'+t.s+'|'+c2+'|'+_f.rc(_f.ref);if(c!=_t.d){var _pcs=ct[4];}else{var _pcs=q;}
_s.cs('ACEUACS',_f.uacs(_pcs),(1000*86400*365)*10,'/','');if((r==_f.rc(_f.url+_f.ref))&&r!=_t.d){rt=1;};if(s==_t.d){a=ts;_s.cs('AS',ts,0,'/','');re=0;v=1;}else{if(c2!=0&&rt!=1){sv[3]=c2;};if(((_f.ti(t.p)-_f.ti(sv[1]))-_u.st)>0){a=ts;_s.cs('AS',a,0,'/','');_s.cs('AR',"0",0,'/','');rt=0;v=1;}else{if(_s.ri()!=1&&rt!=1&&_f.rc(_f.ref)!=sv[4]&&!(v==0&&_f.ref=="bookmark")&&window.location.search.indexOf('aas')<0){a=sv[0]+'|'+t.p+'|'+t.s+'|'+sv[3]+'|'+_f.rc(_f.ref);}else{a=sv[0]+'|'+t.p+'|'+sv[2]+'|'+sv[3]+'|'+sv[4];}
_s.cs('AS',a,0,'/','');v=0;}}
if(v==1){if(c!=_t.d){cn=parseInt(ct[1])+1;if(cn>=11){cn=11;};if(String(ct[4])!=_t.d){q=ct[4];};g=t.s+'|'+cn+'|'+ct[2]+'|'+ct[3]+'|'+q;}else{g=t.s+'|'+cn+'|'+t.s+'|'+cn2+'|'+q;c=t.s+'|0|'+t.s+'|0'+'|'+q;};_s.cs('AU',g,(1000*86400*365)*10,'/','');}
if(c==_t.d||c.indexOf('undefined')>-1||c.indexOf('NaN')>-1){g=sv[0]+'|'+cn+'|'+sv[0]+'|'+cn2+'|'+q;c=sv[0]+'|2|'+sv[0]+'|1'+'|'+q;_s.cs('AU',g,(1000*86400*365)*10,'/','');ct=c.split("|");}
if(c1==1&&ct[0]!=_t.d&&rt!=1){if(String(ct[4])!=_t.d){q=ct[4];};cn2=parseInt(ct[3])+1;g=ct[0]+'|'+ct[1]+'|'+t.s+'|'+cn2+'|'+q;_s.cs('AU',g,(1000*86400*365)*10,'/','');};sts=a.split("|");a=sts[0]+'|'+sts[1]+'|'+sts[2]+'|'+sts[3];return{st:a,vk:v,vt:c,re:rt};},um:function(rs){var rrs=rs+'';var a=0;var u=_u.ud;if(u.indexOf(",")!=-1){u=u.split(',');for(var i=0;i<u.length;i++){if(rrs==u[i])
return 1;}}else{if(rrs==u)
a=1;}
return a;},iE:function(){var i='';if(document.URL.indexOf('acec=')>0){var sta=_s.cg('AS').split('|');_s.cs('AE',sta[1],0,'/','');i=_f.gP('acec');}
var it='';var ic=_s.cg('AE');if(ic!=_t.d){it=ic;}else{it='';}
return{ie:i,iet:it}}};var _s={buy:function(){var s='';var ce='';var g="";var oll=[];var olk=[];var cl=[];var oct=0;var op='';var od='';if(typeof(AM_Cart)!=_t.d){try{ce=m_buy;}catch(_cc){ce='null'};try{om=m_order_code;}catch(_oo){om=''};if(ce!=''&&ce=='finish'){var on=AM_Cart;var ot=[];try{op=m_pay;}catch(_c2){op='';}
od=om;if(om!=''){if(m_order_code==_s.cg('AO')){return'';}else{_s.cs('AO',m_order_code,86400*30*12,'/','');};}
for(var vv in on){if(_f.ct(on[vv])==0){break;}
ot=_f.ct(on[vv]);var PI=String(ot.pn+ot.onm);var nval=cl[PI];cl[PI]={ct:ot.ct,pn:ot.pn,am:parseInt(ot.at)+parseInt((nval)?nval.am:0),qy:parseInt(ot.qy)+parseInt((nval)?nval.qy:0),pd:ot.pd,onm:ot.onm};var ov=cl[PI].ct+'@'+cl[PI].pn+'@'+cl[PI].am+'@'+cl[PI].qy+'@'+cl[PI].pd+'@'+cl[PI].onm;if(!nval){oll.push(ov);olk[PI]=oct;oct++;}else{oll[olk[PI]]=ov;}}
g=oll.join('^');s='&md=b&ll='+_f.e(g)+'&pay='+op+'&onum='+od;};}
return s;},e:function(a){var s='';var r="";var an=0;try{s=eval(a);if(a=='m_amt'){s=s.replace(/[^0-9.]/g,"");};if(a=='m_pd'){s=_f.tgc(s);};if(a=='m_ct'){s=_f.tgc(s);};}catch(_e){s=''};r=_f.e(s);return r;},ri:function(){var r=String(_f.ref);var a=0;r=_f.hr(r,'r');r=r.split('/');if(_f.um(r[0])==1){a=1;}
return a;},ui:_f.um(_f.hr(_f.url,'h')),mi:function(a){var mi=_s.e('m_id');var mj=_s.e('m_jid');var mn=_s.e('m_jn');var cr='';var ct="";if(mn=='join'){if(mj!=""&&_u.py==1){cr='&jid='+mj+'&jn='+_s.e('m_jn');}else if(mj!=""&&_u.py==0){cr='&jid='+_t.um+'&jn='+_s.e('m_jn');}}else if(mn=='withdraw'){cr='&jn='+_s.e('m_jn');}
if(mi!=""&&_u.py==1){ct='&id='+mi;}else if(mi!=""&&_u.py==0){ct='&id='+_t.um;}
return cr+''+ct;},s:(typeof(screen)!=_t.d)&&(typeof(screen.width)==_t.m)?screen.width+'*'+screen.height:'0*0',c:function(){if(_s.cg('AS')!=_t.d){return 1;}else{return 0;}},cd:(typeof(screen)!=_t.d)?((typeof(screen.pixelDepth)!=_u.m)?screen.colorDepth:screen.pixelDepth):_t.d,cs:function(n,v,e,p,d){var ex=new Date();var es='0';if(e!=0){ex.setTime(ex.getTime()+eval(e));es=ex.toGMTString();}
if(_AceCkdm!=''){var _COD=_AceCkdm.split(',');for(var i in _COD){var _CODM=_COD[i];if(window.location.hostname.indexOf(_CODM)>-1){d=_CODM;break;}else{d=window.location.hostname;}}}
d=d.replace(/^(m\.|www\.)/,'');if(n=='ACEUACS'){var s=n+"="+escape(v)+((e!=0)?";expires="+es:"")+((p)?";path="+p:"")+";";}else{var s=n+_u.uid+"="+escape(v)+((e!=0)?";expires="+es:"")+((p)?";path="+p:"")+";domain="+((d)?d+";":_u.cd+";");}
document.cookie=s;},cg:function(v){var aq='';if(v=="_fbc"){var s=v;}else{var s=v+_u.uid;}
var ss=0;var se=0;var dc=document.cookie;if(dc.length>0){ss=dc.lastIndexOf(s+"=");if(ss!=-1){ss=ss+s.length+1;se=dc.indexOf(";",ss);if(se==-1){se=dc.length;};aq=unescape(dc.substring(ss,se));return aq;};}
return _t.d;},re:function(){var r=_s.cg('AR');if(_t.d==String(r)){return 0;}else{if(String(r)==_f.rc(_f.url+_f.ref)){return 1;}
return 0;}}};var _p={pid:'',p:'https://'+_u.gd,s:'/',fcv:function(st,vt){var cs=String(st).split("|");var cv=String(vt).split("|");return cv[4]+'-'+Math.floor(parseInt(String(cs[1]).substr(0,13))/1000)%86400;},lt:function(a,v){var r=''+a;if(r.length>v){r=r.substring(0,v);};return r;},send:function(w,s){if(_s.ui==1){var x=cng='';var nc=new Image(0,0);nc.referrerPolicy='strict-origin-when-cross-origin';var a=_s.buy();var _FBC=_s.cg('_fbc');if(_FBC==_t.d){_FBC='';}
var k=_s.e('m_skey');var n=_f.sse(a,k);var vl='&ui='+_s.ui+_s.mi()+'&ag='+_s.e('m_ag')+'&gd='+_s.e('m_gd')+'&skey='+k+'&pd='+_s.e('m_pd')+'&ct='+_s.e('m_ct')+'&amt='+_s.e('m_amt')+''+a+'&mr='+_s.e('m_mr')+'&cd='+_s.cd+'&tz='+_f.tz()+'&lg='+_f.lg+'&pcm='+_f.pcm+'&ud1='+_s.e('m_ud1')+'&ud2='+_s.e('m_ud2')+'&ud3='+_s.e('m_ud3');var fcv=_p.fcv(n.st,n.vt);var tms='&sv='+_u.sv+'&st='+n.st+'&vt='+n.vt+'&vk='+n.vk+'&ce='+_s.c()+'&FCV='+fcv;var dmp="0.0.0";try{dmp=window._AMSync.dmp();}catch(_ec){}
_s.cs('AR',_f.rc(_f.url+_f.ref),0,'/','');if(typeof(w)!=_t.d){if(w=='site'){x='mwg/?mid='+_u.uid+'&tp=site'+tms+'&ri='+_s.ri()+'&re='+n.re+'&dm='+_s.s+'&acec='+_f.iE().ie+'&ineventts='+_f.iE().iet+'&url='+_f.e(_f.hr(_f.url,'u'))+'&ref='+_f.e(_f.hr(_f.ref,'r'))+''+vl+'&fbc='+_FBC+'&dmp='+dmp;try{window._AcePID=escape(_u.gd+'/mwg/?mid='+_u.uid+'&tp=cart&md=p&FCV='+fcv+'&dm='+location.hostname);}catch(_e){};}else if(w=='link'||w=='tel'){x='mwg/?mid='+_u.uid+'&tp='+w+tms+'&ri='+_s.ri()+'&re='+n.re+'&dm='+_s.s+'&url='+_f.e(_f.hr(_f.url,'u'))+'&ref='+_f.e(_f.hr(s,'r'))+''+vl;}else if(w=='cart'){x='mwg/?mid='+_u.uid+'&tp=cart'+tms+''+s+'&fbc='+_FBC+'&dmp='+dmp;}};nc.src=_p.lt(_p.p+_p.s+x,2048);_AMLog.push(nc);}}};var _c={Run:function(){if(_f.ei(navigator.userAgent,'Chrome/1.')>-1){return 0;};_f.ea('mousedown',this.ec);},ec:function(e){var ok='';var m=document.all?event.srcElement:e.target;if(typeof(m)==_t.d){return true;}
var a=m;if(eval(_t.Lp)){ok=_c.lc(m);if(ok.length!=0){setTimeout("AM_LINK('"+ok+"');",100);};}},lc:function(o){try{var ar='',tf=0,obj=o;var a=o;if(eval(_t.Lp)){obj=_f.f(o);if(_f.d(String(obj.href).substr(0,4))=='TEL:'){ar=obj.href;if(ar!=''){_p.send('tel',ar);return'';};};if(typeof obj.onclick==_t.f){tf=1;ar=String(obj.onclick);}else if(typeof obj!=_t.m){tf=0;if(_AceCkdm!=''&&_AceCrsdm!=''){for(var i in _CSD){var _ht=String(obj.href);if(_f.ei(_ht,'?')!=-1){_ht=_ht.split('?')[0];}
if(_f.ei(_ht,_CSD[i])!=-1&&_f.ei(_ht,_MCD)==-1&&_f.ei(String(obj.href),'aas=')==-1){ar=String(obj.href);var pdd='&';if(_f.ei(ar,'?')==-1){pdd='?';}
var as=_s.cg('AS').split("|");var au=_s.cg('AU').split("|");var are='';if(as[0]!=as[2]){are=as[2];}
obj.href=ar+pdd+'aas='+as[0]+'|'+are+'&aau='+_s.cg('AU');break;}}}
ar=String(obj.href);};if((_f.d(o.tagName)=='IMG')&&(typeof o.onclick==_t.f)){tf=1;ar=String(o.onclick);}}
if(ar.length==0){return'';};ar=_f.n(ar);if(_f.ei(ar,'void(')==-1&&_f.ei(ar,'void0')==-1){if(tf==1){ar=_f.g(ar);if(ar==''){return'';};if(_f.ei(ar,_t.j)==-1){return _t.j+ar;}else{return ar;};}else{return ar;};}else{return _t.j+'void('+_f.nm(ar)+')';};return'';}catch(_e){return'';};}};if(_s.ui==1){_c.Run();_p.send('site','');}
return{vp:function(q){var cu='';if((q!="")&&(q.substr(0,1)=="/")){cu=(_f.hr(_f.url,'h')+''+q);_f.url=cu.replace(/\/\//gi,"/");if(_s.ui==1){_p.send('site','');}}},vt:function(ok){if(_f.d(ok.substr(0,4))=='TEL:'){_p.send('tel',ok);}else{_p.send('link',ok);}},ap:function(q){var ct1=_s.e('m_ct');var pt1=_s.e('m_pd');var pp=String(_s.e('m_amt'));var qt1=q;var pe=0;if((_f.iN(qt1)==true)&&(typeof(pt1)!=_t.d)&&(pt1.length!=0)){pe=parseInt(pp.replace(/[^0-9.]/g,""));var at1=(parseInt(pe))*q;var _At='';_At+=ct1+'@'+pt1+'@'+at1+'@'+qt1+'^';_p.send('cart','&md=i&ll='+_RPS(_f.e(_At),"+","%2B"));}},ac:function(o,p,c,d){var cm='i';var dt=0;var oc=[];var ot=[];var at=0;var _At='';var m=(d)?d:'';oc=o;for(var i in oc){if(_f.ct(oc[i])==0){continue;}
ot=_f.ct(oc[i]);if(arguments.length==1){_At+=ot.ct+'@'+ot.pn+'@'+ot.at+'@'+ot.qy+'^';cm='o';if(_f.e(_At).length>800){_At=_At+'&cmd=on';_p.send('cart','&md=o&ll='+_f.e(_At));_At='';};}else{if(p==i){if(ot.qy!=c||m!=''){dt=c-parseInt(ot.qy);at=Math.round((parseInt(ot.at)/parseInt(ot.qy)));if(dt>0){cm='i';}else{cm='o';};if(m==''){oc[i].am=at*Math.abs(dt);oc[i].qy=Math.abs(dt);}
_At+=ot.ct+'@'+ot.pn+'@'+oc[i].am+'@'+oc[i].qy+'^';if(m=='del'){cm='o';oc[i].qy='0';}
break;}}}}
if(_At.length>0){_p.send('cart','&md='+cm+'&ll='+_RPS(_f.e(_At),"+","%2B"));};}};})();function AM_CUD(){return(typeof(AM_Cart)!='undefined')?1:0;};function AM_PRODUCT(qty){if(typeof(qty)!='undefined'){if(AM_CUD()==0){AM_Mobile.ap(qty);}}};function AM_INOUT(pl,cnt){if(AM_CUD()==1){AM_Mobile.ac(AM_Cart,pl,cnt);}};function AM_DEL(pl,cnt){if(AM_CUD()==1){AM_Mobile.ac(AM_Cart,pl,cnt,'del');}};function AM_CARTDEL(){if(AM_CUD()==1){AM_Mobile.ac(AM_Cart);}};function AM_TEL(n){if(typeof(n)!='undefined'){AM_Mobile.vt(n);}};function AM_LINK(n){if(typeof(n)!='undefined'){AM_Mobile.vt(n);}};function AM_PL(n){if(typeof(n)!='undefined'){if(n.indexOf(';')>0){var _ttRLK=n;var _spt1=n.indexOf(';');var _spt2K=n.indexOf('?');if(_spt1<_spt2K){_ttRLK=_ttRLK.substr(0,_spt1);n=_ttRLK+n.substr(_spt2K,n.length-_spt1);}else{n=n.substr(0,_spt1);}};AM_Mobile.vp(n);}};}}
var _TOAST=(function(tp,u){var si=new Image(0,0),dv='ACEUCI'+tp+'=1',dc=document,lpt='https:';if(String(document.cookie).indexOf('ACEUCI'+tp+'=')==-1){si.src=lpt+'//adlc-exchange.toast.com/sendid?sid=acecounter&uid='+u+'&rnd='+Math.random();};dc.cookie=dv+';';return si;})('','1726056160339217531');
